Trigger rebuild for WordPress

diff --git a/docker/consul/templates/Dockerfile.template b/docker/consul/templates/Dockerfile.template
--- a/docker/consul/templates/Dockerfile.template
+++ b/docker/consul/templates/Dockerfile.template
@@ -27,18 +27,27 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
 ENV GOSU_VERSION {{ $gosu.Version }}
 ENV GOSU_GPG {{ $gosu.Gpg }}
 
-RUN set -x \
-    && wget -q -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
-    && wget -q -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
-    # copy source code
-    && wget -q -O /usr/local/src/gosu.tar.gz "https://github.com/tianon/gosu/archive/$GOSU_VERSION.tar.gz" \
-    # extract gosu binary and check signature
-    && export GNUPGHOME="$(mktemp -d)" \
-    && {{ `gpg --keyserver $server --recv-keys $GOSU_GPG` | KeyServersRetryLoop "\t" }} \
-    && gpg --no-tty --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
-    && rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
-    && chmod +x /usr/local/bin/gosu \
-    && gosu nobody true
+RUN set -ex; \
+    apt-get update; \
+    apt-get install -y --no-install-recommends \
+        ca-certificates \
+        wget \
+        git \
+    ; \
+    \
+    # Install a secure Go version
+    wget -qO- https://go.dev/dl/go1.25.9.linux-amd64.tar.gz | tar -C /usr/local -xzf -; \
+    export PATH=$PATH:/usr/local/go/bin; \
+    \
+    # Compile gosu
+    git clone --depth 1 -b "$GOSU_VERSION" https://github.com/tianon/gosu.git /usr/local/src/gosu; \
+    cd /usr/local/src/gosu; \
+    go build -ldflags '-w -s' -o /usr/local/bin/gosu; \
+    \
+    # Test gosu runs and clean up build dependencies
+    /usr/local/bin/gosu nobody true; \
+    rm -rf /usr/local/go /usr/local/src/gosu; \
+    rm -rf /var/lib/apt/lists/*
 
 # Set up certificates, base tools, and Consul.
 RUN set -eux && \
@@ -52,6 +61,7 @@ RUN set -eux && \
       jq \
     ' && \
     apt-get update && apt-get install -qq -y $buildDependencies \
+      && apt-get install -y --only-upgrade perl zlib1g \
       && gpg --keyserver keyserver.ubuntu.com --recv-keys $CONSUL_GPG
 
 RUN mkdir -p /tmp/build && \
