VM - Kibana - HTTPS settings

diff --git a/vm/chef/cookbooks/kibana/files/kibana-utils b/vm/chef/cookbooks/kibana/files/kibana-utils
--- a/vm/chef/cookbooks/kibana/files/kibana-utils
+++ b/vm/chef/cookbooks/kibana/files/kibana-utils
@@ -35,3 +35,87 @@ function fill_in_config_template() {
   envsubst < "${template_file}.orig" > "${output_file}"
   rm "${template_file}.orig"
 }
+
+function check_password() {
+  local -r hostname="$1"
+  local -r protocol="$2"
+  local -r auth_user="$3"
+  local -r auth_user_pass="$4"
+  local -r endpoint="${protocol}://${hostname}:9200"
+
+  if [[ "${protocol}" == "http" ]]; then
+    response="$(curl -s -u "${auth_user}:${auth_user_pass}" \
+      "${endpoint}" | jq -r '.status')"
+  else
+    response="$(curl -s -k -u "${auth_user}:${auth_user_pass}" \
+      "${endpoint}" | jq -r '.status')"
+  fi
+
+  if [[ "${response}" == "401" ]]; then
+    echo "1"
+  else
+    echo "0"
+  fi
+}
+
+function create_user() {
+  local -r hostname="$1"
+  local -r protocol="$2"
+  local -r auth_user="$3"
+  local -r auth_user_pass="$4"
+  local -r user_to_create="$5"
+  local -r new_pass="$6"
+
+  local -r endpoint="${protocol}://${hostname}:9200/_security/user/${user_to_create}"
+  local response=""
+
+  echo "Creating elasticsearch user"
+
+  if [[ "${protocol}" == "http" ]]; then
+    response="$(curl -X POST \
+      -u "${auth_user}:${auth_user_pass}" \
+      -d "{\"password\":\"${new_pass}\", \"roles\": [\"kibana_admin\"] }" \
+      -H "Content-Type: application/json" \
+      "${endpoint}")"
+  else
+    response="$(curl -k -X POST \
+      -u "${auth_user}:${auth_user_pass}" \
+      -d "{\"password\":\"${new_pass}\", \"roles\": [\"kibana_admin\"] }" \
+      -H "Content-Type: application/json" \
+      "${endpoint}")"
+  fi
+
+  if [[ "${response}" != '{"created":true}' ]]; then
+    echo "User creation failed: ${response}"
+    exit 1
+  fi
+}
+
+function try_to_create_user() {
+  local -r hostname="$1"
+  local -r protocol="$2"
+  local -r auth_user="$3"
+  local -r auth_user_pass="$4"
+  local -r user_to_create="$5"
+  local -r new_pass="$6"
+
+  local check_exit_code=1
+
+  until [[ "${check_exit_code}" == "0" ]]; do
+    sleep 3
+
+    echo "Checking current password..."
+    check_exit_code="$(check_password "${hostname}" "${protocol}" \
+      "${auth_user}" "${auth_user_pass}")"
+
+    if [[ "${check_exit_code}" == "0" ]]; then
+      echo "ES Connection successful."
+      echo "Creating user..."
+      create_user "${hostname}" "${protocol}" \
+        "${auth_user}" "${auth_user_pass}" \
+        "${user_to_create}" "${new_pass}"
+    else
+      echo "ES Invalid credentials"
+    fi
+  done
+}
